# Generated by Django 5.0.3 on 2024-03-24 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('contract_number', models.CharField(blank=True, max_length=150, verbose_name='Номер договора')),
                ('status_choices', models.CharField(blank=True, choices=[('Активна', 'Активна'), ('Бронь', 'Бронь'), ('Куплена', 'Куплена'), ('Расрочка', 'Расрочка'), ('Бартер', 'Бартер')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('full_name', models.CharField(blank=True, max_length=30, verbose_name='full name')),
                ('count', models.CharField(blank=True, max_length=99999, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='manager_groups', related_query_name='manager', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='manager_user_permissions', related_query_name='manager', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджер',
            },
        ),
        migrations.CreateModel(
            name='Apartaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('objects_ap', models.CharField(blank=True, max_length=150, verbose_name='Объект')),
                ('floor', models.IntegerField(blank=True, verbose_name='Этаж')),
                ('ap', models.FloatField(blank=True, verbose_name='Кв')),
                ('date_at', models.DateField(blank=True, verbose_name='Дата')),
                ('status_choices', models.CharField(blank=True, choices=[('Активна', 'Активна'), ('Бронь', 'Бронь'), ('Куплена', 'Куплена'), ('Расрочка', 'Расрочка'), ('Бартер', 'Бартер')], max_length=100, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000000, verbose_name='Цена')),
                ('info', models.CharField(blank=True, max_length=150, verbose_name='Информация о статусе')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.users', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Квартиры',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
