# Generated by Django 5.0.3 on 2024-03-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='count',
            field=models.CharField(blank=True, max_length=99999, null=True, verbose_name='count'),
        ),
    ]
